### ISSUE TITLE
Repository License Missing

### ISSUE THREAD

**Issue by zoccoler** [mathworks/physionet_ECG_data#2]
Hi there,

would it be possible to provide a License to this repository?
In that way, people would know if and in what conditions it would be OK to re-use the data hosted here.

If this is an open dataset, I would suggest BSD-3.

Thanks!

**Comment by wmking** [comment]
The data is not mine to license as the README file states. The data is sourced from physionet.org so you can see PhysioNet for licensing. In keeping with PhysioNet's data reuse policy, a .txt file is included in the zip file which contains all the required attributions, descriptions of data modification, and required citations.  These citations and data descriptions are required by PhysioNet.

**Comment by zoccoler** [comment]
Yes, thanks for clarifying! I have seen that the data came from PhysioNet. I was being cautious and thus I thought it would be better to ask here :)

Maybe having the license here as well instead of only inside the zip file would be more clear, since this repo only hosts those data.
